// Builds index.html at the repo root: the whole site in ONE self-contained file
// (all games, CSS and JS inlined; no network requests). GitHub Pages serves this file.
import { build } from 'esbuild';
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const root = (p) => fileURLToPath(new URL(`../${p}`, import.meta.url));
const pkg = JSON.parse(readFileSync(root('package.json'), 'utf8'));
// Version only (no date) so the build is reproducible: CI rebuilds and checks index.html is up to date.
const stamp = pkg.version;

const result = await build({
  entryPoints: [root('src/app/main.js')],
  bundle: true,
  minify: true,
  format: 'iife',
  target: 'es2020',
  write: false,
  legalComments: 'none',
  define: { __APP_VERSION__: JSON.stringify(stamp) },
  logLevel: 'warning',
});
const js = result.outputFiles[0].text.replace(/<\/script/gi, '<\\/script');

let html = readFileSync(root('src/index.html'), 'utf8');
// Inline every stylesheet in the order src/index.html lists them.
html = html.replace(
  /<link rel="stylesheet" href="([^"]+)">\n?/g,
  (_, href) => `<style>${readFileSync(root(`src/${href}`), 'utf8')}</style>\n`,
);
html = html.replace(/<script type="module" src="app\/main\.js"><\/script>/, () => `<script>${js}</script>`);
html = html.replace(
  '<!-- SOURCE -->',
  `<!-- Built ${stamp} from src/ by scripts/build.mjs. Do not edit this file: edit src/ and run npm run build. -->`,
);
if (/<link rel="stylesheet"|type="module"/.test(html)) throw new Error('build: something was not inlined');
writeFileSync(root('index.html'), html);
console.log(`index.html  ${Math.round(html.length / 1024)} KB  v${stamp}`);
