// Generates src/activities/index.js (one lazy loader per game) from src/content/registry.js.
// Static import() paths let esbuild bundle every game into the single-file build.
// Run automatically by `npm run build`; `npm run check` fails if the file is out of date.
import { writeFileSync, readFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { ACTIVITIES } from '../src/content/registry.js';

const out = fileURLToPath(new URL('../src/activities/index.js', import.meta.url));

export function generateIndex() {
  const lines = ACTIVITIES.map((a) => `  '${a.id}': () => import('./${a.id}.js'),`);
  return [
    '// GENERATED by scripts/gen-index.mjs from src/content/registry.js. Do not edit by hand.',
    '// Run `npm run build` (or `node scripts/gen-index.mjs`) after adding or renaming a game.',
    'export const loaders = {',
    ...lines,
    '};',
    '',
  ].join('\n');
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const text = generateIndex();
  const old = existsSync(out) ? readFileSync(out, 'utf8') : '';
  if (old !== text) writeFileSync(out, text);
  console.log(`src/activities/index.js: ${ACTIVITIES.length} games${old === text ? ' (unchanged)' : ' (updated)'}`);
}
